name: CI Check

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 pytest

      - name: Run flake8 (lint)
        run: flake8 .

      - name: Run black (check formatting)
        run: black --check .

      - name: Run tests (pytest)
        run: pytest -q

- name: Send Telegram message
        if: always()
        run: |
          STATUS="SUCCESS"
          if [ "${{ job.status }}" != "success" ]; then
            STATUS="FAILED"
          fi

          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="CI finished: $STATUS in repo ${{ github.repository }}"
